### PR TITLE
Fix MusicBrainz URL, chapters not used

### LINKED ISSUE #251: MusicBrainz HTTP 404
Note sure if the API was made more strict, but the tool currently uses the release API for a work, which always returns 404.

Current request:
`http://musicbrainz.org/ws/2/release/8669da33-bf9c-47fe-adc9-23798a37b096?inc=recordings&fmt=json`

Should be:
`http://musicbrainz.org/ws/2/work/2293df54-3571-4cb1-9758-a0be7094f988?inc=recording-rels&fmt=json`

### PR DESCRIPTION
**Pull request by cpiber**
Closes #251

### CODE REVIEW

File: src/library/Parser/MusicBrainzChapterParser.php [hunk 1]
```diff
@@ -54,6 +54,11 @@ public function loadRecordings($retries=5, $pause=100000, $callback = 'file_get_
                 ];
 
                 $context = stream_context_create($options);
+                $headers = get_headers($urlToGet, false, $context);
+                if (substr($headers[0], 9, 3) === "404") {
```
Comment (sandreas) [inline src/library/Parser/MusicBrainzChapterParser.php:58]: This is kind of prone to error... but I don't have a better solution, so I'll allow it :-)

**Review by sandreas — APPROVED** [review]
Looks good to me, only the 404 check is a bit dirty. However, thank yo very much for fixing this.

File: src/library/Parser/MusicBrainzChapterParser.php (hunk 1 above)
Comment (cpiber) [reply src/library/Parser/MusicBrainzChapterParser.php:58]: Yep. But I don't think there's a better solution, and PHP should already check that it's a proper HTTP status line
